#!/usr/bin/env bash
# ssh config file

# Host *
# SendEnv LANG LC_*
# HashKnownHosts yes
# GSSAPIAuthentication yes
# GSSAPIDelegateCredentials no
# IdentityFile ~/.ssh/school
# PasswordAuthentication no

OR
Host 34.239.254.183
IdentityFile ~/.ssh/school
PasswordAuthentication no
